-- MySQL Script generated by MySQL Workbench
-- Wed Apr  5 10:03:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto` DEFAULT CHARACTER SET utf8 ;
USE `projeto` ;

-- -----------------------------------------------------
-- Table `projeto`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`Funcionario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `setor_idx` (`id_departamento` ASC) VISIBLE,
  CONSTRAINT `setor`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `projeto`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`Departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `localizacao` VARCHAR(45) NOT NULL,
  `gerente_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `genrencia_idx` (`gerente_id` ASC) VISIBLE,
  CONSTRAINT `genrencia`
    FOREIGN KEY (`gerente_id`)
    REFERENCES `projeto`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`Cliente` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `cpf` CHAR(11) NULL,
  `cnpj` CHAR(14) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`Usuario` (
  `id` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `id_funcionario` INT NULL,
  `id_cliente` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `funcionario_idx` (`id_funcionario` ASC) VISIBLE,
  INDEX `cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `funcionario`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `projeto`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `projeto`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`Chamados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`Chamados` (
  `protocolo` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `id_departamento` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `id_solicitante` INT NOT NULL,
  `id_responsavel` INT NULL,
  `data_abertura` DATE NOT NULL,
  `data_fechamento` DATE NULL,
  `prioridades` VARCHAR(45) NULL,
  `prazo` DATE NOT NULL,
  PRIMARY KEY (`protocolo`),
  INDEX `setor_idx` (`id_departamento` ASC) VISIBLE,
  INDEX `solicitante_idx` (`id_solicitante` ASC) VISIBLE,
  INDEX `responsavel_idx` (`id_responsavel` ASC) VISIBLE,
  CONSTRAINT `setor2`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `projeto`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `solicitante`
    FOREIGN KEY (`id_solicitante`)
    REFERENCES `projeto`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `responsavel`
    FOREIGN KEY (`id_responsavel`)
    REFERENCES `projeto`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
