-- MySQL Script generated by MySQL Workbench
-- Sun May  7 17:17:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto-backend
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto-backend
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto-backend` DEFAULT CHARACTER SET utf8 ;
USE `projeto-backend` ;

-- -----------------------------------------------------
-- Table `projeto-backend`.`Setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto-backend`.`Setor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `localizacao` VARCHAR(45) NOT NULL,
  `gerente_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `genrencia_idx` (`gerente_id` ASC) VISIBLE,
  CONSTRAINT `genrencia`
    FOREIGN KEY (`gerente_id`)
    REFERENCES `projeto-backend`.`Funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto-backend`.`Urgencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto-backend`.`Urgencia` (
  `dias` INT NOT NULL,
  `escala` INT NOT NULL,
  PRIMARY KEY (`escala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto-backend`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto-backend`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `setor` VARCHAR(45) NULL,
  `telefone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto-backend`.`Chamados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto-backend`.`Chamados` (
  `protocolo` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `id_setor` INT NULL,
  `tipo` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `id_usuario` INT NOT NULL,
  `nome_solicitante` VARCHAR(60) NOT NULL,
  `email_solicitante` VARCHAR(60) NOT NULL,
  `telefone_solicitante` VARCHAR(45) NOT NULL,
  `id_responsavel` INT NULL,
  `data_abertura` DATE NOT NULL,
  `data_fechamento` DATE NULL,
  `urgencia` INT NULL,
  `prazo` DATE NULL,
  `data_prazo` DATE NULL,
  PRIMARY KEY (`protocolo`),
  INDEX `setor_idx` (`id_setor` ASC) VISIBLE,
  INDEX `chamado_urgencia_idx` (`urgencia` ASC) VISIBLE,
  INDEX `chamado_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `email_usuario_idx` (`email_solicitante` ASC) VISIBLE,
  INDEX `telefone_usuario_idx` (`telefone_solicitante` ASC) VISIBLE,
  CONSTRAINT `chamado_setor`
    FOREIGN KEY (`id_setor`)
    REFERENCES `projeto-backend`.`Setor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chamado_urgencia`
    FOREIGN KEY (`urgencia`)
    REFERENCES `projeto-backend`.`Urgencia` (`escala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chamado_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `projeto-backend`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `email_usuario`
    FOREIGN KEY (`email_solicitante`)
    REFERENCES `projeto-backend`.`Usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `telefone_usuario`
    FOREIGN KEY (`telefone_solicitante`)
    REFERENCES `projeto-backend`.`Usuario` (`telefone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto-backend`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto-backend`.`Cargo` (
  `nome` VARCHAR(45) NOT NULL,
  `id_setor` INT NULL,
  PRIMARY KEY (`nome`),
  INDEX `cargo_setor_idx` (`id_setor` ASC) VISIBLE,
  CONSTRAINT `cargo_setor`
    FOREIGN KEY (`id_setor`)
    REFERENCES `projeto-backend`.`Setor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
