-- MySQL Script generated by MySQL Workbench
-- Sun Jun 11 11:42:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto-backend
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `projeto-backend` DEFAULT CHARACTER SET utf8 ;
USE `projeto-backend` ;

-- -----------------------------------------------------
-- Table `projeto-backend`.`Cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto-backend`.`Cargo` ;

CREATE TABLE IF NOT EXISTS `projeto-backend`.`Cargo` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `id_setor` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `cargo_setor`
    FOREIGN KEY (`id_setor`)
    REFERENCES `projeto-backend`.`Setor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `projeto-backend`.`Chamados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto-backend`.`Chamados` ;

CREATE TABLE IF NOT EXISTS `projeto-backend`.`Chamados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL DEFAULT 'Pendente',
  `tipo` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `id_setor` INT NULL,
  `id_usuario` INT NOT NULL,
  `id_responsavel` INT NULL,
  `data_abertura` DATE NOT NULL,
  `data_fechamento` DATE NULL,
  `urgencia` INT NULL,
  `prazo` DATE NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `chamado_setor`
    FOREIGN KEY (`id_setor`)
    REFERENCES `projeto-backend`.`Setor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chamado_urgencia`
    FOREIGN KEY (`urgencia`)
    REFERENCES `projeto-backend`.`Urgencia` (`escala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_chamado`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `projeto-backend`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `responsavel_chamado`
    FOREIGN KEY (`id_responsavel`)
    REFERENCES `projeto-backend`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `projeto-backend`.`Setor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto-backend`.`Setor` ;

CREATE TABLE IF NOT EXISTS `projeto-backend`.`Setor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `gerente_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `gerencia_setor`
    FOREIGN KEY (`gerente_id`)
    REFERENCES `projeto-backend`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `projeto-backend`.`Urgencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto-backend`.`Urgencia` ;

CREATE TABLE IF NOT EXISTS `projeto-backend`.`Urgencia` (
  `escala` INT NOT NULL,
  `dias` INT NOT NULL,
  PRIMARY KEY (`escala`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `projeto-backend`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projeto-backend`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `projeto-backend`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `cargo` INT NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `cargo_usuario`
    FOREIGN KEY (`cargo`)
    REFERENCES `projeto-backend`.`Cargo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
